name: Deploy to IOT_UTILITY_SERVER

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.IOT_UTILITY_PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.IOT_UTILITY_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to IOT_UTILITY
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.IOT_UTILITY_USER }}@${{ secrets.IOT_UTILITY_HOST }} << 'EOF'
          cd ~/iotiq_utilities
          git pull origin master
          sudo npm i
          sudo npm run build
          sudo pm2 restart 0
        EOF
